### ISSUE TITLE
悬浮球问题

### ISSUE THREAD

**Issue by xing403** [baday19/HiLoop#1]
在实现悬浮球拖拽时，我看代码中给`document`绑定了`mousemove` 事件，我最近也在实现这个功能，这个鼠标移动的事件坐标不是连续的(当鼠标拖拽缓慢是没有影响的，但如果拖动很快的就会造成鼠标移出这个窗口导致悬浮球移动并未紧跟鼠标移动{断触的效果})，
自己试了一些方法例如给元素使用`-webkit-app-region: drag;` 确实实现了拖拽，但点击事件并未触发，有没有更好的方法能将悬浮球显示更为丝滑

**Comment by baday19** [comment]
你好，由于近期很忙并且代码太久远并不能很好的回答你的问题。但是在我的实际测试中，我所实现的悬浮球是可以快速拖动并且正常点击的。如果你有兴趣可以尝试跑通我的代码，看看这项功能在你的环境下是否正常。如果正常也许你能得到一些启发；如果不正常，我非常希望得到你的反馈，我将在空闲的时候深入探索一下这个问题。

**Comment by xing403** [comment]
你的是可以的 😢
